create table if not exists public.company_profiles (
    id bigint generated by default as identity primary key,
    company_name text not null default '',
    company_description text not null default '',
    sales_markets text not null default '',
    primary_business_activity text not null default '',
    categories text not null default '',
    events text not null default '',
    address text not null default '',
    email text not null default '',
    telephone text not null default '',
    website text not null default ''
);

alter table public.company_profiles enable row level security;

grant select on public.company_profiles to anon, authenticated, service_role;

drop policy if exists "Public can read company profiles"
    on public.company_profiles;
create policy "Public can read company profiles"
    on public.company_profiles
    for select
    to anon, authenticated
    using (true);

create or replace function public.replace_company_profiles(profiles jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    imported_count integer;
begin
    truncate table public.company_profiles restart identity;

    insert into public.company_profiles (
        company_name,
        company_description,
        sales_markets,
        primary_business_activity,
        categories,
        events,
        address,
        email,
        telephone,
        website
    )
    select
        coalesce(item.company_name, ''),
        coalesce(item.company_description, ''),
        coalesce(item.sales_markets, ''),
        coalesce(item.primary_business_activity, ''),
        coalesce(item.categories, ''),
        coalesce(item.events, ''),
        coalesce(item.address, ''),
        coalesce(item.email, ''),
        coalesce(item.telephone, ''),
        coalesce(item.website, '')
    from jsonb_to_recordset(profiles) as item(
        company_name text,
        company_description text,
        sales_markets text,
        primary_business_activity text,
        categories text,
        events text,
        address text,
        email text,
        telephone text,
        website text
    );

    get diagnostics imported_count = row_count;
    return imported_count;
end;
$$;

revoke all on function public.replace_company_profiles(jsonb)
    from public, anon, authenticated;
grant execute on function public.replace_company_profiles(jsonb)
    to service_role;
